name: 150Birmingham
favicon: null
layout_spectrum: 0.9971223354805261
typography_spectrum: 0.03755985083989799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e71b1c'
    - '#ffffff'
    - '#000000'
    - '#8c8c8c'
    - '#c7c7c7'
  brandStrength: 0.6270792970899493
  lightness: 0.42815740476362407
  saturation: 0.37366052879951894
  rhythmicContrast: 0.6623104601167142
purpose: []
